    
[package]
name = "OWLAlexa"
version = "0.1.0"
authors = ["David <awesomesauce712@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.16"
serde_json = "1.0"
json = "0.11.13"
chrono = "0.4"
mockito = "0.17.1"